#!/bin/bash

sudo iptables -A INPUT -p tcp --dport 3306 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo /opt/lampp/xampp start
sleep 20
mysql -u root -e "SET GLOBAL event_scheduler = ON" -S /opt/lampp/var/mysql/mysql.sock
